os:
  - linux
  - osx
dist: trusty
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly
  - pypy3
  - pypy3-nightly
before_install:
  - pip3 install --upgrade setuptools setuptools_scm coveralls
install:
  - python setup.py install
script:
  - coverage run --source=Cache python tests/test.py test
after_success:
  - coveralls
